export { default as HomePage } from '@pages/HomePage';
export { default as SearchPage } from '@pages/SearchPage';
export { default as LoginPage } from '@pages/LoginPage';
export { default as SignUpPage } from '@pages/SignUpPage';
export { default as CreatePostPage } from '@pages/CreatePostPage';
export { default as MyPage } from '@pages/MyPage';
export { default as UserPage } from '@pages/UserPage';
export { default as PostPage } from '@pages/PostPage';
export { default as NotFoundPage } from '@pages/NotFoundPage';
